#!/usr/bin/env python3
"""Generate sv0c/lib/sha256.sv0: SHA-256 in sv0 for the compiler (CV-104).

sv0cov decision D-2: coverage point and map IDs are SHA-256 digests computed by
the compiler itself, in sv0 source, so both the native and the VM-built
compiler can emit maps.

Representation. Every 32-bit word is held as two i32 halves in 0..65535
(``xh`` high, ``xl`` low). Additions sum halves and propagate one carry, so no
intermediate exceeds 2^19: nothing relies on signed-overflow wrap, which is
undefined in the generated C (plain ``int``, no ``-fwrapv``). Rotations and
shifts mask before shifting left. The message schedule is a rolling window of
16 words in locals and the round constants come from a ``match``, so hashing
allocates no Vec, slice, or string-table handle; only the 64-character hex
result is built with ``string_concat``.

Input is the bytes of an sv0 ``str`` (``string_char_at`` yields 0..255).
Strings cannot contain NUL, which the coverage formats forbid anyway.

The file has no ``module`` line: compiler library files are concatenated into
one translation unit (mega-TU), so every name is prefixed ``sha256_``.

    python3 sv0c/scripts/gen_sha256_sv0.py          # check (exit 1 if stale)
    python3 sv0c/scripts/gen_sha256_sv0.py --write
"""

from __future__ import annotations

import sys
from pathlib import Path

OUT = Path(__file__).resolve().parents[1] / "lib" / "sha256.sv0"

K = [
    0x428A2F98, 0x71374491, 0xB5C0FBCF, 0xE9B5DBA5, 0x3956C25B, 0x59F111F1, 0x923F82A4, 0xAB1C5ED5,
    0xD807AA98, 0x12835B01, 0x243185BE, 0x550C7DC3, 0x72BE5D74, 0x80DEB1FE, 0x9BDC06A7, 0xC19BF174,
    0xE49B69C1, 0xEFBE4786, 0x0FC19DC6, 0x240CA1CC, 0x2DE92C6F, 0x4A7484AA, 0x5CB0A9DC, 0x76F988DA,
    0x983E5152, 0xA831C66D, 0xB00327C8, 0xBF597FC7, 0xC6E00BF3, 0xD5A79147, 0x06CA6351, 0x14292967,
    0x27B70A85, 0x2E1B2138, 0x4D2C6DFC, 0x53380D13, 0x650A7354, 0x766A0ABB, 0x81C2C92E, 0x92722C85,
    0xA2BFE8A1, 0xA81A664B, 0xC24B8B70, 0xC76C51A3, 0xD192E819, 0xD6990624, 0xF40E3585, 0x106AA070,
    0x19A4C116, 0x1E376C08, 0x2748774C, 0x34B0BCB5, 0x391C0CB3, 0x4ED8AA4A, 0x5B9CCA4F, 0x682E6FF3,
    0x748F82EE, 0x78A5636F, 0x84C87814, 0x8CC70208, 0x90BEFFFA, 0xA4506CEB, 0xBEF9A3F7, 0xC67178F2,
]
H0 = [0x6A09E667, 0xBB67AE85, 0x3C6EF372, 0xA54FF53A, 0x510E527F, 0x9B05688C, 0x1F83D9AB, 0x5BE0CD19]
LETTERS = "abcdefgh"


def _check_constants() -> None:
    """K and H0 are the fractional parts of cube and square roots of the first primes."""
    primes = [p for p in range(2, 312) if all(p % q for q in range(2, int(p**0.5) + 1))][:64]

    def frac_root(p: int, k: int) -> int:
        lo, hi = 0, 1 << 40  # integer k-th root of p * 2^(32k), then keep 32 fractional bits
        target = p << (32 * k)
        while lo < hi:
            mid = (lo + hi + 1) // 2
            if mid**k <= target:
                lo = mid
            else:
                hi = mid - 1
        return lo & 0xFFFFFFFF

    assert K == [frac_root(p, 3) for p in primes], "K constants"
    assert H0 == [frac_root(p, 2) for p in primes[:8]], "H0 constants"


def generate() -> str:
    _check_constants()
    out: list[str] = []
    w = out.append
    w("/* sv0c SHA-256 (FIPS 180-4), generated by sv0c/scripts/gen_sha256_sv0.py; do not edit.")
    w(" * sha256_hex(s) = lowercase hex SHA-256 of the bytes of s (sv0cov D-2, CV-104).")
    w(" * 32-bit words are pairs of 16-bit halves in i32 locals; see the generator's")
    w(" * docstring for why (no reliance on signed overflow, no Vec allocation).")
    w(" */")
    w("")
    # round constants
    for part, shift in (("hi", 16), ("lo", 0)):
        w(f"fn sha256_k_{part}(t: i32) -> i32 {{")
        w("  return match t {")
        for i, k in enumerate(K):
            w(f"    {i} => {(k >> shift) & 0xFFFF},")
        w("    _ => 0,")
        w("  };")
        w("}")
        w("")
    # rotate right / shift right on (h, l) halves
    w("fn sha256_pow2(n: i32) -> i32 {")
    w("  let mut p = 1;")
    w("  let mut i = 0;")
    w("  while i < n {")
    w("    p = p * 2;")
    w("    i = i + 1;")
    w("  };")
    w("  return p;")
    w("}")
    w("")
    w("/* (x >> n) combined with the low n bits of y moved to the top: 0 < n < 16, x and y in 0..65535. */")
    w("fn sha256_mix(x: i32, y: i32, n: i32) -> i32 {")
    w("  let m = sha256_pow2(n);")
    w("  return x / m + (y % m) * sha256_pow2(16 - n);")
    w("}")
    w("")
    w("fn sha256_rotr_hi(h: i32, l: i32, n: i32) -> i32 {")
    w("  if n >= 16 {")
    w("    return sha256_rotr_hi(l, h, n - 16);")
    w("  };")
    w("  if n == 0 {")
    w("    return h;")
    w("  };")
    w("  return sha256_mix(h, l, n);")
    w("}")
    w("")
    w("fn sha256_rotr_lo(h: i32, l: i32, n: i32) -> i32 {")
    w("  if n >= 16 {")
    w("    return sha256_rotr_lo(l, h, n - 16);")
    w("  };")
    w("  if n == 0 {")
    w("    return l;")
    w("  };")
    w("  return sha256_mix(l, h, n);")
    w("}")
    w("")
    w("fn sha256_shr_hi(h: i32, l: i32, n: i32) -> i32 {")
    w("  return h / sha256_pow2(n);")
    w("}")
    w("")
    w("fn sha256_shr_lo(h: i32, l: i32, n: i32) -> i32 {")
    w("  return sha256_mix(l, h, n);")
    w("}")
    w("")
    # sigma functions
    for name, a, b, c, shr in (("big0", 2, 13, 22, False), ("big1", 6, 11, 25, False), ("small0", 7, 18, 3, True), ("small1", 17, 19, 10, True)):
        for part in ("hi", "lo"):
            third = f"sha256_shr_{part}(h, l, {c})" if shr else f"sha256_rotr_{part}(h, l, {c})"
            w(f"fn sha256_{name}_{part}(h: i32, l: i32) -> i32 {{")
            w(f"  return sha256_rotr_{part}(h, l, {a}) ^ sha256_rotr_{part}(h, l, {b}) ^ {third};")
            w("}")
            w("")
    w("fn sha256_ch(e: i32, f: i32, g: i32) -> i32 {")
    w("  return (e & f) ^ ((e ^ 65535) & g);")
    w("}")
    w("")
    w("fn sha256_maj(a: i32, b: i32, c: i32) -> i32 {")
    w("  return (a & b) ^ (a & c) ^ (b & c);")
    w("}")
    w("")
    # padded message bytes
    w("/* Byte i of the padded message: data, 0x80, zeros, then the 64-bit big-endian bit length. */")
    w("fn sha256_byte(s: str, n: i32, total: i32, i: i32) -> i32 {")
    w("  if i < n {")
    w("    return string_char_at(s, i);")
    w("  };")
    w("  if i == n {")
    w("    return 128;")
    w("  };")
    w("  let k = total - 1 - i;")
    w("  if k >= 8 {")
    w("    return 0;")
    w("  };")
    w("  if k == 0 {")
    w("    return (n % 32) * 8;")
    w("  };")
    w("  if k >= 5 {")
    w("    return 0;")
    w("  };")
    w("  return (n / sha256_pow2(8 * k - 3)) % 256;")
    w("}")
    w("")
    w("fn sha256_word_hi(s: str, n: i32, total: i32, i: i32) -> i32 {")
    w("  return sha256_byte(s, n, total, i) * 256 + sha256_byte(s, n, total, i + 1);")
    w("}")
    w("")
    w("fn sha256_word_lo(s: str, n: i32, total: i32, i: i32) -> i32 {")
    w("  return sha256_byte(s, n, total, i + 2) * 256 + sha256_byte(s, n, total, i + 3);")
    w("}")
    w("")
    w("fn sha256_hex4(x: i32) -> str {")
    w('  let digits = "0123456789abcdef";')
    w("  let mut out = \"\";")
    w("  let mut shift = 4096;")
    w("  while shift > 0 {")
    w("    out = string_concat(out, string_substr(digits, (x / shift) % 16, 1));")
    w("    shift = shift / 16;")
    w("  };")
    w("  return out;")
    w("}")
    w("")
    # main function
    w("fn sha256_hex(s: str) -> str {")
    w("  let n = string_len(s);")
    w("  let total = ((n + 8) / 64 + 1) * 64;")
    for i, x in enumerate(H0):
        w(f"  let mut h{i}h = {x >> 16};")
        w(f"  let mut h{i}l = {x & 0xFFFF};")
    w("  let mut off = 0;")
    w("  while off < total {")
    for j in range(16):
        w(f"    let mut w{j}h = sha256_word_hi(s, n, total, off + {4 * j});")
        w(f"    let mut w{j}l = sha256_word_lo(s, n, total, off + {4 * j});")
    for i, c in enumerate(LETTERS):
        w(f"    let mut {c}h = h{i}h;")
        w(f"    let mut {c}l = h{i}l;")
    w("    let mut t = 0;")
    w("    while t < 64 {")
    # T1 = h + S1(e) + ch(e,f,g) + K[t] + W[t]
    w("      let t1lsum = hl + sha256_big1_lo(eh, el) + sha256_ch(el, fl, gl) + sha256_k_lo(t) + w0l;")
    w("      let t1l = t1lsum % 65536;")
    w("      let t1h = (hh + sha256_big1_hi(eh, el) + sha256_ch(eh, fh, gh) + sha256_k_hi(t) + w0h + t1lsum / 65536) % 65536;")
    w("      let t2lsum = sha256_big0_lo(ah, al) + sha256_maj(al, bl, cl);")
    w("      let t2l = t2lsum % 65536;")
    w("      let t2h = (sha256_big0_hi(ah, al) + sha256_maj(ah, bh, ch) + t2lsum / 65536) % 65536;")
    w("      hh = gh;")
    w("      hl = gl;")
    w("      gh = fh;")
    w("      gl = fl;")
    w("      fh = eh;")
    w("      fl = el;")
    w("      let elsum = dl + t1l;")
    w("      el = elsum % 65536;")
    w("      eh = (dh + t1h + elsum / 65536) % 65536;")
    w("      dh = ch;")
    w("      dl = cl;")
    w("      ch = bh;")
    w("      cl = bl;")
    w("      bh = ah;")
    w("      bl = al;")
    w("      let alsum = t1l + t2l;")
    w("      al = alsum % 65536;")
    w("      ah = (t1h + t2h + alsum / 65536) % 65536;")
    # schedule: W[t+16] = s1(w14) + w9 + s0(w1) + w0
    w("      let nlsum = sha256_small1_lo(w14h, w14l) + w9l + sha256_small0_lo(w1h, w1l) + w0l;")
    w("      let nl = nlsum % 65536;")
    w("      let nh = (sha256_small1_hi(w14h, w14l) + w9h + sha256_small0_hi(w1h, w1l) + w0h + nlsum / 65536) % 65536;")
    for j in range(15):
        w(f"      w{j}h = w{j + 1}h;")
        w(f"      w{j}l = w{j + 1}l;")
    w("      w15h = nh;")
    w("      w15l = nl;")
    w("      t = t + 1;")
    w("    };")
    for i, c in enumerate(LETTERS):
        w(f"    let s{i} = h{i}l + {c}l;")
        w(f"    h{i}l = s{i} % 65536;")
        w(f"    h{i}h = (h{i}h + {c}h + s{i} / 65536) % 65536;")
    w("    off = off + 64;")
    w("  };")
    w('  let mut out = "";')
    for i in range(8):
        w(f"  out = string_concat(out, sha256_hex4(h{i}h));")
        w(f"  out = string_concat(out, sha256_hex4(h{i}l));")
    w("  return out;")
    w("}")
    return "\n".join(out) + "\n"


def main() -> int:
    text = generate()
    if "--write" in sys.argv:
        OUT.write_text(text)
        print(f"gen_sha256_sv0: wrote {OUT}")
        return 0
    if not OUT.is_file() or OUT.read_text() != text:
        print(f"gen_sha256_sv0: {OUT} is stale; run with --write", file=sys.stderr)
        return 1
    print("gen_sha256_sv0: current")
    return 0


if __name__ == "__main__":
    sys.exit(main())
